spring:
  application:
    name: distancelearning-notification-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: distancelearning-config-server
      username: adminconfig
      password: 'adminconfig'